spring:
  application:
    name: tilas-web-mangement
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tilas
    username: root
    password: 1234
  servlet:
    multipart:
      max-file-size: 10MB
mybatis:
  configuration:
#    开启数据库访问的日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    开启数据库字段与实体类属性之间驼峰映射
    map-underscore-to-camel-case: true
#指定xml映射文件位置:类路径(java或者resources)下Mapper文件夹xml文件
  mapper-locations: classpath:Mapper/*.xml

#配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

#阿里云oss配置
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: java-wcx
    region: cn-beijing
